language: node_js
node_js":
  - 16.15
  - 12.0

services:
  - docker

script:
  - docker-compose -f docker-compose-build.yaml build --parallel

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: main