#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
#docker tag udagram-api-feed sudkul/udagram-api-feed:v1
#docker push sudkul/udagram-api-feed:v1
docker image prune --all
docker-compose -f docker-compose-build.yaml build --parallel



