#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
docker tag udagram-api-feed edwardmuss/udagram-api-feed:v1
docker tag udagram-api-user edwardmuss/udagram-api-user:v1
docker tag udagram-frontend edwardmuss/udagram-frontend:v1
docker push edwardmuss/udagram-api-feed:v1
docker push edwardmuss/udagram-api-user:v1
docker push edwardmuss/udagram-frontend:v1
# docker-compose -f docker-compose-build.yaml build --parallel



